name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build with Grunt
      run: grunt

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages-${{ matrix.node-version }}
        path: ./dist

    - name: Deploy to GitHub Pages
      if: ${{ matrix.node-version == '22.x' }}
      id: deployment 
      uses: actions/deploy-pages@v3
